<?php

namespace ContainerJvgn5xq;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DaWzMElService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.daWzMEl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.daWzMEl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'planner' => ['privates', '.errored..service_locator.daWzMEl.App\\Entity\\Planner', NULL, 'Cannot autowire service ".service_locator.daWzMEl": it needs an instance of "App\\Entity\\Planner" but this type has been excluded in "config/services.yaml".'],
        ], [
            'planner' => 'App\\Entity\\Planner',
        ]);
    }
}
