<?php

namespace ContainerJvgn5xq;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PtUEmELService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PtUEmEL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PtUEmEL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'meal' => ['privates', '.errored..service_locator.PtUEmEL.App\\Entity\\Meals', NULL, 'Cannot autowire service ".service_locator.PtUEmEL": it needs an instance of "App\\Entity\\Meals" but this type has been excluded in "config/services.yaml".'],
            'mealsRepository' => ['privates', 'App\\Repository\\MealsRepository', 'getMealsRepositoryService', true],
        ], [
            'entityManager' => '?',
            'meal' => 'App\\Entity\\Meals',
            'mealsRepository' => 'App\\Repository\\MealsRepository',
        ]);
    }
}
