<?php

namespace ContainerJvgn5xq;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlannerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.daWzMEl.App\Entity\Planner' shared service.
     *
     * @return \App\Entity\Planner
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.daWzMEl": it needs an instance of "App\\Entity\\Planner" but this type has been excluded in "config/services.yaml".');
    }
}
