<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Meals extends \App\Entity\Meals implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'approved' => [parent::class, 'approved', null],
        "\0".parent::class."\0".'calories' => [parent::class, 'calories', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'image' => [parent::class, 'image', null],
        "\0".parent::class."\0".'imageSize' => [parent::class, 'imageSize', null],
        "\0".parent::class."\0".'ingredients' => [parent::class, 'ingredients', null],
        "\0".parent::class."\0".'link' => [parent::class, 'link', null],
        "\0".parent::class."\0".'mealType' => [parent::class, 'mealType', null],
        "\0".parent::class."\0".'nutriensTable' => [parent::class, 'nutriensTable', null],
        "\0".parent::class."\0".'preparationTime' => [parent::class, 'preparationTime', null],
        "\0".parent::class."\0".'recipe' => [parent::class, 'recipe', null],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null],
        'approved' => [parent::class, 'approved', null],
        'calories' => [parent::class, 'calories', null],
        'fk_user' => [parent::class, 'fk_user', null],
        'id' => [parent::class, 'id', null],
        'image' => [parent::class, 'image', null],
        'imageFile' => [parent::class, 'imageFile', null],
        'imageSize' => [parent::class, 'imageSize', null],
        'ingredients' => [parent::class, 'ingredients', null],
        'link' => [parent::class, 'link', null],
        'mealName' => [parent::class, 'mealName', null],
        'mealType' => [parent::class, 'mealType', null],
        'nutriensTable' => [parent::class, 'nutriensTable', null],
        'preparationTime' => [parent::class, 'preparationTime', null],
        'recipe' => [parent::class, 'recipe', null],
        'updatedAt' => [parent::class, 'updatedAt', null],
    ];

    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {
        if ($cloner !== null) {
            return;
        }

        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'id' => true,
            'imageFile' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
