<?php

namespace Container5EoBdI2;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IeXg_XFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ieXg.xF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ieXg.xF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'planner' => ['privates', '.errored..service_locator.ieXg.xF.App\\Entity\\Planner', NULL, 'Cannot autowire service ".service_locator.ieXg.xF": it needs an instance of "App\\Entity\\Planner" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'planner' => 'App\\Entity\\Planner',
        ]);
    }
}
