<?php

namespace Container5EoBdI2;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NEt2DqoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nEt2Dqo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nEt2Dqo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'meal' => ['privates', '.errored..service_locator.nEt2Dqo.App\\Entity\\Meals', NULL, 'Cannot autowire service ".service_locator.nEt2Dqo": it needs an instance of "App\\Entity\\Meals" but this type has been excluded in "config/services.yaml".'],
        ], [
            'meal' => 'App\\Entity\\Meals',
        ]);
    }
}
