<?php

namespace Container5EoBdI2;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMealsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.PtUEmEL.App\Entity\Meals' shared service.
     *
     * @return \App\Entity\Meals
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.PtUEmEL": it needs an instance of "App\\Entity\\Meals" but this type has been excluded in "config/services.yaml".');
    }
}
