<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJvgn5xq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJvgn5xq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJvgn5xq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJvgn5xq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJvgn5xq\App_KernelDevDebugContainer([
    'container.build_hash' => 'Jvgn5xq',
    'container.build_id' => '776752d3',
    'container.build_time' => 1719485743,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJvgn5xq');
